development:
  adapter: sqlite3
  database: db/db_development
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/db_test
  timeout: 5000

production:
  adapter: mysql2
  host: typo.cy42tayowjsy.us-east-1.rds.amazonaws.com
  username: typo
  password: Save0404
  database: typo

cucumber:
  <<: *test

