development:
  adapter: sqlite3
  database: db/db_development
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/db_test
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  username: root
  password: Yin512
  database: typo

cucumber:
  <<: *test